FROM golang:1.21 as build-stage

WORKDIR /app

COPY .. .

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/interlink

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11:latest AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/interlink /interlink

USER nonroot:nonroot

ENTRYPOINT ["/interlink"]
