FROM bitnami/kubectl as kubectl

FROM golang:1.21 as build-stage

WORKDIR /app

COPY .. .

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/vk cmd/virtual-kubelet/main.go

# Deploy the application binary into a lean image
FROM ubuntu:22.04 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/vk /vk

COPY --from=kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/

ENTRYPOINT ["/vk"]
